POST localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGVtYWlsLmNvbSIsImV4cCI6MTcwMzkyMjQ3MywidXNlcklkIjoyfQ.3wMhwxi-uxEQ1fQQgyqqihfFVMp0FUKnpYzuKCOMHnQ

{
  "title": "Старый новый год",
  "description": "Старый новый год 2024",
  "location": "Друзья",
  "dateTime": "2024-01-01T00:00:00.000Z"
}