POST localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiZXhwIjoxNzAzODY0MDc4LCJ1c2VySWQiOjF9.HMof-qH8l7SLVO6rovCCF4CBBIbcjDDc361veQ1fn9U

{
  "title": "Старый новый год",
  "description": "Старый новый год 2024",
  "location": "Друзья",
  "dateTime": "2024-01-01T00:00:00.000Z"
}