DELETE localhost:8080/events/2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGVtYWlsLmNvbSIsImV4cCI6MTcwMzg1ODMxNiwidXNlcklkIjoyfQ.lOIiv7Tq2GbKmPQZDHGzQ_oqDS63ilPgCnav9VmwGYI
